version: '3'

services:
  provider:
    image: fint/provider:latest
    ports:
      - "8230:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /felles/kodeverk/provider
      fint.events.orgIds: "fint.health,fint.felles.kodeverk"
      fint.events.component: beta
      fint.events.env: beta
      fint.events.redisson.addresses: "redis://redis:6379"
      fint.events.redisson.use-linux-native-epoll: "true"
      fint.events.reddison.dns-monitoring: "true"
      fint.audit.mongo.hostname: fint-mongodb
      fint.audit.mongo.databasename: fint-audit-beta
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - fint_shared
      - fint_beta
    depends_on:
      - redis

  consumer:
    image: dtr.rogfk.no/fint-beta/consumer-felles-kodeverk:latest
    ports:
      - "8231:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /felles/kodeverk
      fint.events.orgIds: "fint.health,fint.felles.kodeverk"
      fint.events.component: beta
      fint.events.env: beta
      fint.events.redisson.addresses: "redis://redis:6379"
      fint.events.redisson.use-linux-native-epoll: "true"
      fint.events.reddison.dns-monitoring: "true"
      fint.relations.default-base-url: "https://beta.felleskomponent.no"
      fint.audit.mongo.hostname: fint-mongodb
      fint.audit.mongo.databasename: fint-audit-beta
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - fint_shared
      - fint_beta
    depends_on:
      - redis
      - provider

  felles-kodeverk-adapter:
    image: dtr.rogfk.no/fint-beta/adapter-felles-kodeverk:latest
    environment:
      TZ: Europe/Oslo
      springfox.title: "Felles kodeverk Adapter"
      fint.adapter.organizations: fint.felles.kodeverk
      fint.adapter.sse-endpoint: https://beta.felleskomponent.no/felles/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: https://beta.felleskomponent.no/felles/kodeverk/provider/status
      fint.adapter.response-endpoint: https://beta.felleskomponent.no/felles/kodeverk/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - redis
      - provider

  health-adapter:
    image: fint/health-adapter:latest
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: https://beta.felleskomponent.no/felles/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: https://beta.felleskomponent.no/felles/kodeverk/provider/status
      fint.adapter.response-endpoint: https://beta.felleskomponent.no/felles/kodeverk/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - redis
      - provider

  redis:
    image: redis:3.2.8-alpine
    environment:
      TZ: Europe/Oslo
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - fint_beta

networks:
  fint_beta_vigokodeverk:
    driver: overlay
    external: false
  fint_shared:
    external: true
