version: '3'

services:
  provider:
    image: fint/provider:latest
    ports:
      - "8230:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /felles/kodeverk/provider
      fint.events.orgIds: "fint.health,fint.felles.kodeverk"
      fint.events.component: beta
      fint.events.env: beta
      fint.events.redisson.addresses: "redis://redis:6379"
      fint.events.redisson.use-linux-native-epoll: "true"
      fint.events.reddison.dns-monitoring: "true"
      fint.audit.test-mode: "true"
    depends_on:
      - redis

  consumer:
    build: .
    ports:
      - "8231:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /felles/kodeverk
      fint.events.orgIds: "fint.health,fint.felles.kodeverk"
      fint.events.component: beta
      fint.events.env: beta
      fint.events.redisson.addresses: "redis://redis:6379"
      fint.events.redisson.use-linux-native-epoll: "true"
      fint.events.reddison.dns-monitoring: "true"
      fint.relations.default-base-url: "http://10.0.75.1:8231"
      fint.audit.test-mode: "true"
      fint.consumer.cache-manager: hazelcast
    depends_on:
      - redis
      - provider

  adapter:
    build: ../fint-adapter-felles-kodeverk/
    environment:
      TZ: Europe/Oslo
      springfox.title: "Felles kodeverk Adapter"
      fint.adapter.organizations: fint.felles.kodeverk
      fint.adapter.sse-endpoint: http://10.0.75.1:8230/felles/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: http://10.0.75.1:8230/felles/kodeverk/provider/status
      fint.adapter.response-endpoint: http://10.0.75.1:8230/felles/kodeverk/provider/response
    depends_on:
      - redis
      - provider

  health-adapter:
    image: fint/health-adapter:latest
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: http://10.0.75.1:8230/felles/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: http://10.0.75.1:8230/felles/kodeverk/provider/status
      fint.adapter.response-endpoint: http://10.0.75.1:8230/felles/kodeverk/provider/response
    depends_on:
      - redis
      - provider

  redis:
    image: redis:3.2.8-alpine
    environment:
      TZ: Europe/Oslo
